CREATE DATABASE STUDENT_MANAGEMENT;
USE STUDENT_MANAGEMENT;
CREATE TABLE RECORDS(
ID INT PRIMARY KEY auto_increment,
NAME VARCHAR (50) NOT NULL,
AGE INT NOT NULL,
BRANCH varchar(25),
SGPA INT,
CONTACT VARCHAR(50)
);
select * from records;



